default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: root
  port: 5432

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: task_manager_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: task_manager_api_production
  username: task_manager_api
  password: <%= ENV["TASK_MANAGER_API_DATABASE_PASSWORD"] %>
